"""add_deadline_events_and_sync_log

Revision ID: 4b42fea88b8e
Revises: 673585175e4d
Create Date: 2026-06-05 00:09:37.970134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b42fea88b8e'
down_revision: Union[str, Sequence[str], None] = '673585175e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('sub_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('program_title', sa.String(length=500), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_sessions.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadline_events_event_date'), 'deadline_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_deadline_events_event_type'), 'deadline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_deadline_events_status'), 'deadline_events', ['status'], unique=False)
    op.create_index(op.f('ix_deadline_events_sub_type'), 'deadline_events', ['sub_type'], unique=False)
    op.create_index(op.f('ix_deadline_events_user_id'), 'deadline_events', ['user_id'], unique=False)
    op.create_table('deadline_sync_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('events_count', sa.Integer(), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_sessions.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_column('user_sessions', 'deadlines_cached_at')
    op.drop_column('user_sessions', 'deadlines_cache_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('deadlines_cache_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_sessions', sa.Column('deadlines_cached_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_table('deadline_sync_log')
    op.drop_index(op.f('ix_deadline_events_user_id'), table_name='deadline_events')
    op.drop_index(op.f('ix_deadline_events_sub_type'), table_name='deadline_events')
    op.drop_index(op.f('ix_deadline_events_status'), table_name='deadline_events')
    op.drop_index(op.f('ix_deadline_events_event_type'), table_name='deadline_events')
    op.drop_index(op.f('ix_deadline_events_event_date'), table_name='deadline_events')
    op.drop_table('deadline_events')
    # ### end Alembic commands ###
