"""add_programs_cache_to_user_sessions

Revision ID: 673585175e4d
Revises: d7c57cb3d98c
Create Date: 2026-05-31 18:27:45.729759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '673585175e4d'
down_revision: Union[str, Sequence[str], None] = 'd7c57cb3d98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('programs_cache_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_sessions', sa.Column('programs_cached_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'programs_cached_at')
    op.drop_column('user_sessions', 'programs_cache_json')
    # ### end Alembic commands ###
