"""add_summary_module_tables

Revision ID: 900479648d05
Revises: 2d60fe661c56
Create Date: 2026-06-10 17:48:11.116203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '900479648d05'
down_revision: Union[str, Sequence[str], None] = '2d60fe661c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netology_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('netology_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('program_type', sa.String(length=20), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_sessions.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netology_programs_netology_id'), 'netology_programs', ['netology_id'], unique=False)
    op.create_index(op.f('ix_netology_programs_user_id'), 'netology_programs', ['user_id'], unique=False)
    op.create_table('netology_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('netology_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['netology_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netology_modules_program_id'), 'netology_modules', ['program_id'], unique=False)
    op.create_table('netology_lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('netology_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['netology_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netology_lessons_module_id'), 'netology_lessons', ['module_id'], unique=False)
    op.create_table('netology_lesson_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('netology_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('has_vtt', sa.Boolean(), nullable=False),
    sa.Column('vtt_extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['netology_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netology_lesson_items_item_type'), 'netology_lesson_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_netology_lesson_items_lesson_id'), 'netology_lesson_items', ['lesson_id'], unique=False)
    op.create_table('conspects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_item_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('module_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('raw_vtt', sa.Text(), nullable=True),
    sa.Column('compressed_text', sa.Text(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_item_id'], ['netology_lesson_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['netology_modules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['netology_programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_sessions.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conspects_lesson_item_id'), 'conspects', ['lesson_item_id'], unique=False)
    op.create_index(op.f('ix_conspects_user_id'), 'conspects', ['user_id'], unique=False)
    op.create_table('conspect_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_item_id', sa.UUID(), nullable=False),
    sa.Column('conspect_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conspect_id'], ['conspects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_item_id'], ['netology_lesson_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_sessions.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conspect_jobs_lesson_item_id'), 'conspect_jobs', ['lesson_item_id'], unique=False)
    op.create_index(op.f('ix_conspect_jobs_status'), 'conspect_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_conspect_jobs_user_id'), 'conspect_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conspect_jobs_user_id'), table_name='conspect_jobs')
    op.drop_index(op.f('ix_conspect_jobs_status'), table_name='conspect_jobs')
    op.drop_index(op.f('ix_conspect_jobs_lesson_item_id'), table_name='conspect_jobs')
    op.drop_table('conspect_jobs')
    op.drop_index(op.f('ix_conspects_user_id'), table_name='conspects')
    op.drop_index(op.f('ix_conspects_lesson_item_id'), table_name='conspects')
    op.drop_table('conspects')
    op.drop_index(op.f('ix_netology_lesson_items_lesson_id'), table_name='netology_lesson_items')
    op.drop_index(op.f('ix_netology_lesson_items_item_type'), table_name='netology_lesson_items')
    op.drop_table('netology_lesson_items')
    op.drop_index(op.f('ix_netology_lessons_module_id'), table_name='netology_lessons')
    op.drop_table('netology_lessons')
    op.drop_index(op.f('ix_netology_modules_program_id'), table_name='netology_modules')
    op.drop_table('netology_modules')
    op.drop_index(op.f('ix_netology_programs_user_id'), table_name='netology_programs')
    op.drop_index(op.f('ix_netology_programs_netology_id'), table_name='netology_programs')
    op.drop_table('netology_programs')
    # ### end Alembic commands ###
