"""add_full_name_and_avatar_url_to_user_sessions

Revision ID: d7c57cb3d98c
Revises: 9e04552096c7
Create Date: 2026-05-31 16:12:36.412595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c57cb3d98c'
down_revision: Union[str, Sequence[str], None] = '9e04552096c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('user_sessions', sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'avatar_url')
    op.drop_column('user_sessions', 'full_name')
    # ### end Alembic commands ###
